
cablenostalgia_wordlist = [
    ['Doraemon', 'Our favourite from the future'],
    ['Shinchan', '~~burri burri burri burri~~'],
    ['TomandJerry', 'An evergreen childhood classic'],
    ['OggyandtheCockroaches', 'Tom & Jerry but 3 roaches'],
    ['ChotaBheem', 'Laddoo.'],
    ['MickeyMouseclubhouse', 'Toodles!'],
    ['Pokemon', '"____, I choose you!'],
    ['NinjaHattori', '"pahadon ke upar jungle ke paas"'],
    ['Teletubbies', 'SuN bAbY'],
    ['Scoobydoo', 'Shaggy\'s true brother'],
    ['WinniethePooh', 'Hunny.'],
    ['MrBean', 'Can never seperate him from his Teddy'],
    ['Powerpuffgirls', '3 girls, 1 bad monkey'],
    ['Ben10', 'Watch, alien, watching an alien'],
    ['Spongebob', 'Pineapple.'],
    ['Smurfs', 'Blue dwarfs'],
    ['PinkPanther', ''],
    ['BobtheBuilder', '"CaN wE fIx iT??"'],
    ['PhineasandFerb', "There's a 104 days of summer vacation"],
    ['HorridHenry', 'Typical siblings in every household but make it white'],
    ['MotuPatlu', 'Naariyal anna']
]

food_wordlist = [
    ['MasalaDosa', 'The best version of dosa'],
    ['BisiBeleBath', 'Always need boondi'],
    ['MysorePak', 'Has Yaduveer\'s empire dwelling in it'],
    ['Pulihora', 'Every Telugite has this in their blood'],
    ['Avakaya', 'The king of pickles made of king of fruits'],
    ['VadaPav', 'Mumbaikar\'s sandwich'],
    ['Dhokla', 'Gujrati mains'],
    ['Ghevar', 'Jodhpur sweets'],
    ['Khakhra', 'Slim cracker of Gujrat'],
    ['Pakoda', 'Typical monsoon snack'],
    ['Chai', 'Famous train beverage'],
    ['Uttapam', 'South Indian pizza'],
    ['Pongal', 'Pots and sugarcane'],
    ['Biryani', 'Non-veg origin vegetable rice'],
    ['CholeBhature', 'Most satisfactory form of puri'],
    ['Jalebi', 'The most famous street sweet'],
    ['Lassi', 'Healthy and heavy drink'],
    ['Paratha', 'The most verastile Indian bread'],
    ['Ootychocolates', 'The chocolates from South Indian Switzerland'],
    ['MangaluruBuns', 'Malanadu sweet bread'],
    ['GulabJamun', 'Rose going to the moon'],
    ['Rasgulla', 'Most non-Bengali\'s will mis-spell this'],
    ['RajKachori', 'King of snacks in Rajasthan'],
    ['Momos', 'Spicy version of modak']
]


indmyth_wordlist = [
    ['Varaha', 'Kantara'],
    ['Kalki', 'The last one of Vishnu'],
    ['Ravana', 'The greatest villian ever'],
    ['Ahalya','Indra\'s love'],
    ['Dushshala', '101th Kaurava'],
    ['Mahabharatha', 'Epic by Ved Vyasa'],
    ['Draupadi','Was harrased in the kingdom'],
    ['Ekalavya','His thumb'],
    ['Abhimanyu','The first Pandu Putra to die'],
    ['Shakuni','Has biased dice in Ludo and uncrowned a wholeass kingdom'],
    ['Karna','Famous for Charity'],
    ['Krishna', 'Famous for raasleela'],
    ['Dronacharya','One of the greatest guru of all times'],
    ['Dushyasana','The second Duryodhana'],
    ['Tandava','The dance of Nataraja'],
    ['Trimurti','A triune deity and the supreme god of Hinduism'],
    ['Vedas','Ancient scriptures in Sanskrit'],
    ['Jatayu','The bird that tries to save Sita from the forest'],
    ['PushpakaVimana','The first ancestors of flights'],
    ['NaradaMuni','The Sanchari of the universe']
]

space_wordlist = [
    ['BlackHole','whatever enters is lost forever'],
    ['Comet','icy small astronomical object'],
    ['ShootingStar', 'common name for meteor'],
    ['Asteriod', 'rocks in space'],
    ['Planets', 'the main pawns of astrology'],
    ['Galaxy', 'Samsung _____'],
    ['Aliens', 'Jadoo.'],
    ['Spaceship','Sailer of the Space Seas'],
    ['Sattelite', 'the only man-made object in space'],
    ['ISRO', 'The Pride of India in the space domain'],
    ['Astronaut', '"ROlling dOwN iN tHe dEep"'],
    ['NeilArmstrong', 'Gave a souvenir to the Moon'],
    ['Exosphere', 'the outermost region of a planet\'s atmosphere.'],
    ['Debris', 'takes the most space in space'],
    ['Eclipse', 'phenomena of one celestial body covering the other'],
    ['Orbit', 'space chewing gum'],
    ['Supernova' 'explosion of a star']
]

korean_wordlist = [
    ['Hanbok', 'Traditional wear of Korea'],
    ['Gangnam', '"Oppan ___ Style!!"'],
    ['Seoul', 'Captain Korea'],
    ['Ramen', 'Korean version of Netflix and chill'],
    ['Kimchi', 'Korean pickle'],
    ['Soju', 'Korean shots'],
    ['Vincenzo', 'Italian consigliere'],
    ['Hanguel', 'Korean in Korean'],
    ['Hwarang', 'The only K-drama in which BTS features'],
    ['Squid Game','Dalgona coffee.'],
    ['True Beauty', '"Beauty lies within."'],
    ['BLACKPINK', '" _____ in your area"'],
    ['TWICE', 'The girliest of the girl K-pop groups'],
    ['BTS', 'The definition of K-pop'],
    ['EXO', 'E, 23rd letter, O'],
    ['Jeju', 'The richest place in South Korea'],
    ['Tteobokki', 'Partner of Soju'],
    ['Annyeong', 'Hi~~'],
    ['Gomawo!', 'Thanks! (informal)'],
    ['Mianhae', 'Apologies (informal)']
]

marvel_wordlist = [
    ['CaptainAmerica','The 1st Avenger'],
    ['TonyStark', '"Genius, Billionare, Playboy, Philanthropist"'],
    ['Hulk', '"Alpha, Beta, _____"'],
    ['Thor', 'The True Owner of Stormbreaker'],
    ['GuardiansoftheGalaxy', 'Galaxy Protectors'],
    ['Antman', '"As far as I am concerned, that\'s America\'s ass."'],
    ['DoctorStrange', 'as a cloak cooler than Harry Potter'],
    ['AgentCarter', 'The English Bosslady'],
    ['SpiderMan', 'The literal kid of the Avengers'],
    ['Wakanda', '"_____ forever."'],
    ['BlackWidow', '"Sacrifices for her best friend."'],
    ['ScarletWitch', 'Her boys mean everything to her'],
    ['Groot', '"I am ____"'],
    ['Rocket', 'The coolest animal in the Marvel'],
    ]

sports_wordlist = [
    ['Cricket', 'runs in the blood of every Indian'],
    ['Football', 'SIUUUUUUU!!!'],
    ['Badminton', 'The gully sport of Indian aunties'],
    ['Tennis', 'Ball Badminton'],
    ['Squash', 'associated with juice'],
    ['Basketball', 'play this to "increase your height"'],
    ['Rafting', 'high speed water sport'],
    ['HOCKEY', 'dynamic golf'],
    ['Golf', 'static hockey'],
    ['Boxing', 'continuous tense of box'],
    ['Chess', 'the board battleground'],
    ['SNG', 'star water sport'],
    ['Archery', '"Our cherry"'],
    ['Karate', 'HyAHHH!!'],
    ['Skiing', 'one of the most famous winter sport'],
    ['Surfing', 'water skating'],
    ['Bowling', 'target sport but with pins'],
    ['Handball', 'opposite of football'],
    ['Billiards', 'Carrom but with a stick'],
    ['Kabbadi', 'without telling the game\'s name you cannot play it']
    ]